### ISSUE TITLE
Upgrade equals to ^1.0.0

### ISSUE THREAD

**Issue by richardbutler** [pouchdb/pouchdb-replicator#1]
Hi Marten

There's an issue with 0.3.x of `equals` where it's linking to a Github dependency (`jkroso/type#1.1.0`). This causes a headache behind certain proxies that block github.com (e.g. within bank IT infrastructure :), where `pouchdb-replicator` can't be installed as a result.

Please can you test against v1.x of `equals` and, if everything checks out, upgrade and publish to NPM? I'd submit a PR, but have no idea how you would go about testing it.

**Comment by marten-de-vries** [comment]
Sorry, only seeing this now. #3 includes a fix.
